#!/usr/bin/env python3

"""
Welcome to command line snake! 

How to play:
    Steer with WASD.
    Press q at any time to exit.

Modes:
    Regular mode:
        Steer with WASD, each tick the snake will advance one tile.

    Manual mode:
        Steer with WASD. Each time a key is pressed, the snake will advance one tile.
        Any key can be pressed to advance the snake. j and k work well.

    Solve:
        Sit back and relax while the game plays itself in front of your eyes!
        Exit early with CTRL+C



usage: snake [-h] [--mode {regular,manual,solver}] [-r] [-m] [-s] [-a]

Play snake from the command line

options:
  -h, --help            show this help message and exit
  --mode {regular,manual,solver}
                        play game in specified game mode defaults to manual
  -r                    play game in regular mode
  -m                    play game in manual mode
  -s                    watch as the game plays itself
  -a, --auto            automatically start a new game on crash

open an issue at https://github.com/alscwha2/scripts/issues

TODO:
    [] find a way to make the output display normally when using threads
    [] implement regular mode with one thread
    [] track high scores
    [] allow arrow keys to be used instead of WASD
    [] ensure that the game works with odd sized boards
    [] display instructions during gameplay
    [] refactor collision checks
    [] re-implement game win
    [] early exit from solver

Notes:
    * Collision and eating checks are done in the move_head function
    * Trying to move the head into the position of the tail will cause a collision.
"""
import os
import termios
import tty
import sys
import random
import argparse
from threading import Thread
from time import sleep

################################################################################
########################### Constants ##########################################
################################################################################

# game parameters
BOARD_SIZE = 18
INITIAL_SNAKE_LENGTH = 5
SOLVER_TICK_SPEED = 0.05
TICK = 0.2
AUTO_NEW_GAME = False # may be set by supplying -a --auto argument

# directions
UP, RIGHT, DOWN, LEFT = (-1, 0), (0, 1), (1, 0), (0, -1)

# snake pieces
HORIZONTAL, VERTICAL = '\u2550', '\u2551'
BOTTOM_LEFT, BOTTOM_RIGHT, TOP_LEFT, TOP_RIGHT = '\u255A', '\u255D', '\u2554', '\u2557'


################################################################################
########################### GLOBAL VARIABLES ###################################
################################################################################

board = [[]]
empty_tiles = []

head = (0, 0)
tail = (0, 0)
snake_length = INITIAL_SNAKE_LENGTH

next_direction = RIGHT
head_direction = RIGHT
tail_direction = RIGHT

crashed = False
ate = False

################################################################################
########################### FUNCTION DEFINITIONS ###############################
################################################################################

############################### BOARD ##########################################


def initialize_empty_board():
    global board
    board = [[' ' for _ in range(BOARD_SIZE)] for __ in range(BOARD_SIZE)]

    # add borders
    for i in range(1, BOARD_SIZE - 1):
        # add vertical boarders
        board[i][0] = board[i][BOARD_SIZE - 1] = '\u2502'
        # add horizontal boarders
        board[0][i] = board[BOARD_SIZE - 1][i] = '\u2500'

    # add corners
    board[0][0] = '\u250c'
    board[0][BOARD_SIZE - 1] = '\u2510'
    board[BOARD_SIZE - 1][BOARD_SIZE - 1] = '\u2518'
    board[BOARD_SIZE - 1][0] = '\u2514'


def read_board_char(coordinates):
    i, j = coordinates
    return board[i][j]


def write_board_char(coordinates, char):
    i, j = coordinates
    global board
    board[i][j] = char


def place_food():
    new_food_tile = random.choice(empty_tiles)
    write_board_char(new_food_tile, "X")


################################# SNAKE #######################################


def move(end, direction):
    return end[0] + direction[0], end[1] + direction[1]


def initialize_snake():
    global head, tail

    head = BOARD_SIZE // 2, BOARD_SIZE // 2
    write_board_char(head, HORIZONTAL)
    empty_tiles.remove(head)

    tail = head
    for _ in range(INITIAL_SNAKE_LENGTH - 1):
        tail = move(tail, LEFT)
        write_board_char(tail, HORIZONTAL)
        empty_tiles.remove(tail)


######################################## HEAD ##################################


def bend_neck(direction):
    if (head_direction, direction) in {(UP, RIGHT), (LEFT, DOWN)}:
        return TOP_LEFT
    elif (head_direction, direction) in {(DOWN, RIGHT), (LEFT, UP)}:
        return BOTTOM_LEFT
    elif (head_direction, direction) in {(RIGHT, UP), (DOWN, LEFT)}:
        return BOTTOM_RIGHT
    elif (head_direction, direction) in {(UP, LEFT), (RIGHT, DOWN)}:
        return TOP_RIGHT
    elif (head_direction, direction) in {(UP, UP), (DOWN, DOWN)}:
        return VERTICAL
    elif (head_direction, direction) in {(RIGHT, RIGHT), (LEFT, LEFT)}:
        return HORIZONTAL


def check_ate():
    global ate
    ate = read_board_char(head) == 'X'


def check_crash():
    global crashed
    crashed = read_board_char(head) not in {" ", "X"}


def move_head(direction):
    global head, head_direction

    # if you're changing direction, bend the snake's neck in that direction
    write_board_char(head, bend_neck(direction))

    head_direction = direction
    head = move(head, direction)

    # before overwriting the piece, check if it's food or a crash
    check_ate()
    check_crash()

    # place head piece in the new head
    write_board_char(head, VERTICAL if head_direction in {UP, DOWN} else HORIZONTAL)

    if not crashed:
        empty_tiles.remove(head)


##################################### TAIL #####################################


def read_tail_char():
    i, j = tail
    return board[i][j]


def update_tail_direction(tail_char):
    global tail_direction
    if tail_char == BOTTOM_RIGHT:
        if tail_direction == RIGHT:
            tail_direction = UP
        elif tail_direction == DOWN:
            tail_direction = LEFT
    elif tail_char == TOP_RIGHT:
        if tail_direction == UP:
            tail_direction = LEFT
        elif tail_direction == RIGHT:
            tail_direction = DOWN
    elif tail_char == TOP_LEFT:
        if tail_direction == LEFT:
            tail_direction = DOWN
        elif tail_direction == UP:
            tail_direction = RIGHT
    elif tail_char == BOTTOM_LEFT:
        if tail_direction == DOWN:
            tail_direction = RIGHT
        elif tail_direction == LEFT:
            tail_direction = UP


def update_tail():
    if not ate:
        global tail, tail_direction
        # increment tail
        write_board_char(tail, ' ')
        empty_tiles.append(tail)
        tail = move(tail, tail_direction)

        # check if tail is changing direction, update accordingly
        tail_char = read_tail_char()
        if tail_char in {BOTTOM_RIGHT, BOTTOM_LEFT, TOP_RIGHT, TOP_LEFT}:
            update_tail_direction(tail_char)


############################# GAME INITIALIZATION ###############################

def initialize_variables():
    global crashed, ate, snake_length
    crashed = False
    ate = False
    snake_length = INITIAL_SNAKE_LENGTH

    global next_direction, head_direction, tail_direction
    next_direction = RIGHT
    head_direction = RIGHT
    tail_direction = RIGHT

    global empty_tiles
    empty_tiles = [(i, j) for i in range(1, BOARD_SIZE-1) for j in range(1, BOARD_SIZE-1)]


def initialize_game():
    initialize_variables()
    initialize_empty_board()
    initialize_snake()
    place_food()

############################# DRAW GAME ########################################

def draw_board():
    os.system('clear')
    string = ''
    for i in range(BOARD_SIZE):
        for j in range(BOARD_SIZE):
            piece = read_board_char((i, j))
            if j == 0 or j == BOARD_SIZE-1:
                string += piece
            else:
                string += board[i][j]*2
        string += '\n'
    print(string)


def print_score():
    print(f'SCORE: {snake_length}')


def print_game():
    draw_board()
    print_score()


############################# EXECUTE COMMANDS #################################


def get_char():
    # https://stackoverflow.com/questions/14890997/redirect-stdout-to-a-file-only-for-a-specific-thread
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(sys.stdin.fileno())
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch


def change_direction(command):
    global next_direction
    if command == 'w' and head_direction != DOWN:
        next_direction = UP
    elif command == 'a' and head_direction != RIGHT:
        next_direction = LEFT
    elif command == 's' and head_direction != UP:
        next_direction = DOWN
    elif command == 'd' and head_direction != LEFT:
        next_direction = RIGHT


def execute(command):
    if command in {'w', 'a', 's', 'd'}:
        change_direction(command)
    if command == 'q':
        sys.exit(0)


def watch_and_execute_commands():
    while not crashed:
        command = get_char()
        execute(command)


############################## RUN GAME ########################################


def update_game():
    # update head before tail. Head will collide with tail when trying to occupy
    #   the tile that the end of the tail is currently occupying.
    # This behavior is consistent with the Google Snake implementation.
    # To change this behavior, switch the order of the next two function calls.
    move_head(next_direction)
    update_tail()
    if ate:
        global snake_length
        snake_length += 1
        try:
            place_food()
        except IndexError:  # if there are no more empty tiles to place food, you win
            global crashed
            crashed = True
            print_game()
            print("You Win!")


def update_game_loop():
    while not crashed:
        print_game()
        sleep(TICK)
        update_game()

################################################################################
############################# PLAY GAME ########################################
################################################################################

def ask_play_again():
    print("Game Over!\nPlay Again? (y/n)")

    while True:
        command = get_char()
        if command == "y":
            return
        elif command == "n":
            sys.exit(0)

def regular_mode():
    Thread(target=update_game_loop, daemon=True).start()
    Thread(target=watch_and_execute_commands).start()

def manual_mode():
    while True:
        if crashed:
            if not AUTO_NEW_GAME:
                ask_play_again()
            initialize_game()

        print_game()
        command = get_char()
        execute(command)
        update_game()


################################################################################
############################# SOLVER ###########################################
################################################################################


def get_next_solution_step():
    row, column = head

    top_row = 1
    leftmost_column = 1
    second_row = 2
    bottom_row = BOARD_SIZE - 2
    rightmost_column = BOARD_SIZE - 2

    if head_direction == RIGHT:
        return   DOWN if row == second_row \
            else UP if row == bottom_row \
            else UP if column == rightmost_column \
            else RIGHT

    elif head_direction == DOWN:
        return   RIGHT if row == bottom_row \
            else DOWN

    elif head_direction == LEFT:
        return   DOWN if column == leftmost_column \
            else LEFT

    elif head_direction == UP:
        return   LEFT if row == top_row \
            else UP if column == rightmost_column \
            else RIGHT if row == second_row \
            else UP


def solve():
    global next_direction
    while not crashed:
        print_game()
        sleep(SOLVER_TICK_SPEED)
        next_direction = get_next_solution_step()
        update_game()


################################################################################
############################# APPLICATION LOGIC ################################
################################################################################

def parse_args():
    default_game_mode = 'manual'

    parser = argparse.ArgumentParser(
            prog="snake",
            description="Play snake from the command line",
            epilog='open an issue at https://github.com/alscwha2/scripts/issues')
    parser.add_argument('--mode', 
                        choices=['regular', 'manual', 'solver'], 
                        default=default_game_mode,
                        help=f'play game in specified game mode\ndefaults to {default_game_mode}')
    parser.add_argument('-r',
                        action='store_const', const='regular', dest='mode', help='play game in regular mode')
    parser.add_argument('-m',
                        action='store_const', const='manual', dest='mode', help='play game in manual mode')
    parser.add_argument('-s',
                        action='store_const', const='solver', dest='mode', help='watch as the game plays itself')
    parser.add_argument('-a', '--auto',
                        action='store_true', help='automatically start a new game on crash')
    return parser.parse_args()

def main():
    args = parse_args()
    global AUTO_NEW_GAME
    AUTO_NEW_GAME = args.auto

    initialize_game()
    if args.mode == 'manual':
        manual_mode()
    elif args.mode == 'solver':
        solve()
    elif args.mode == 'regular':
        regular_mode()

main()
